config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :schedules

  resources :bookings

  resources :spaces do
    member do
      get :add_booking_to
    end
  end

  resources :users

  root 'home#index'

end

app/models/space.rb
class Space < ActiveRecord::Base
  belongs_to :user
  has_many :bookings
  has_many :schedules

  geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	before_save :capitalise

	def capitalise
		self.address = self.address.titleize
		
	end
	
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:add_booking_to, :show, :edit, :update, :destroy]


  def add_booking_to
    @date = params[:date]
    @space.bookings << Booking.new
    @booking = @space.bookings.last
    @booking.update_attribute(date: @date)
    redirect_to :back
  end
  # GET /spaces
  # GET /spaces.json
  def index
    if params[:search]
      @nearby_locations = Space.near(params[:search], 5)
    else
      @spaces = Space.all
    end
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
    @schedule = Schedule.new
    @date_today = Date.today
    @day_today = Time.now.wday
    @days_of_week = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    @dates_of_week_1 = []
    @days_of_week.each_with_index do |day_of_week, index|
      @dates_of_week_1 << Date.today - (Date.today.wday.to_i - (index + 1))
    end

  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)
    @space.user_id = 1

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:address, :user_id)
    end
end

app/helpers/spaces_helper.rb
module SpacesHelper
	def booking_details(booking)
		booking.date + ' ' + booking.start_time.to_s + ' -> ' + booking.end_time.to_s
	end
end

app/views/spaces/_form.html.erb
<%= form_for(@space) do |f| %>
  <% if @space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% @space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render 'form' %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<h1>Listing spaces</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.address %></td>
        <td><%= space.user %></td>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render 'form' %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @space.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @space.user.name %>
</p>

<p>List of schedules:</p>
<ul>
	<% @space.schedules.each do |schedule| %>
		<li><%= schedule.day_of_week %> (<%= schedule.start_time %> - <%= schedule.end_time %>)</li>
	<% end %>
</ul>

<table class="table table-bordered table-responsive">
	<tr>
<% @days_of_week.each do |day_of_week| %>
	<th width="150px"><%= day_of_week %></th>
<% end %>
	</tr>
	<tr>
		<% @dates_of_week_1.each do |date| %>
			<td style="text-align:center;" class="<%= 'past-date' if date < Date.today %>"><%= date.strftime('%d %b %y') %></td>

		<% end %>
	</tr>
	<tr>
		<% @dates_of_week_1.each_with_index do |date, index| %>
			<td>
				<% if date >= Date.today %>
					
					<% @space.schedules.where('day_of_week = ?', date.wday).each do |schedule| %>
						<a href="#" class="btn btn-success btn-block"><%= schedule.start_time + ' - ' + schedule.end_time %></li>

					<% end %>
					
				<% end %>
		<% end %>
	</tr>
	<tr>
		<% @dates_of_week_1.each do |date| %>
			<td style="text-align:center;" class=""><%= (date + 7).strftime('%d %b %y') %></td>

		<% end %>
	</tr>
	<tr>
		<% @dates_of_week_1.each_with_index do |date, index| %>
			<td>
				<% @space.schedules.where('day_of_week = ?', date.wday).each do |schedule| %>
						
						<%= link_to schedule.start_time + ' - ' + schedule.end_time, add_booking_to_space_path(date: date), class: 'btn btn-success btn-block' %>
					<% end %>
		<% end %>

	</tr>
</table>
<br>
<ul>
<% @space.bookings.each do |booking| %>
	<li><%= booking_details(booking) %></li>
<% end %>
</ul>



<hr>
<table class="table table-bordered table-responsive">
	<tr>
<% @days_of_week.each do |day_of_week| %>
	<th width="150px"><%= day_of_week %></th>
<% end %>
	</tr>
	<tr>
		<% @dates_of_week_1.each_with_index do |date, index| %>
			<td>Start time: 00:00 <br>
			End time: 00:00 <br><button type="button" data-toggle="modal" data-target=".class<%= index %>">Edit</button>
			</td>
		<% end %>
	</tr>


</table>

<hr>
<% @dates_of_week_1.each_with_index do |date, index| %>
<div class="modal fade form<%= index %>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <%= form_for(@schedule) do |f| %>
	 <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>


  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    </div>
  </div>
</div>
<% end %>





<hr>
<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>
<script>
$('#myModal').modal(options)
</script>