config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :schedules

  resources :bookings

  resources :spaces do
    member do
      get :add_booking_to
    end
  end

  resources :users

  root 'home#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :space
  belongs_to :user

 
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    if params[:block]
      @block = true
    end
    if params[:space]
      @space = Space.find(params[:space])
    else
      redirect_to root_path
    end
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user



    respond_to do |format|
      if @booking.save
        if @booking.space.user == current_user
          @booking.update_attribute('self_booking', true)
        end
        format.html { redirect_to :back, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:date, :start_time, :end_time, :space_id, :user_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :space_id %><br>
    <%= f.text_field :space_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>

  <% if @block %>
    <%= f.input :self_booking, checked_value: true %>
  <% end %>



User clicks a button
  Creates a self booking for the space

  add_self_booking_path(space: @space.id, date: date, start_time: time1, end_time: time2)

  resources :bookings do
    member do
      get add_self
    end
  end

  def add_self
    @space = Space.find(params[:space])
    @date = params[:date].to_date
    @start_time = params[:time].to_time
    @booking = Booking.new(space_id: Space.find(params[:space]), date: params[:date].to_date, self_booking: true)
    @booking.save






  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Space</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.date %></td>
        <td><%= booking.start_time %></td>
        <td><%= booking.end_time %></td>
        <td><%= booking.space %></td>
        <td><%= booking.user %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= render @bookings %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Date:</strong>
  <%= @booking.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @booking.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @booking.end_time %>
</p>

<p>
  <strong>Space:</strong>
  <%= @booking.space %>
</p>

<p>
  <strong>User:</strong>
  <%= @booking.user %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>