config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :schedules

  resources :bookings

  resources :spaces do
    member do
      get :add_booking_to
    end
  end

  resources :users

  root 'home#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :space
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  layout 'spaces', only: :show
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    # if params[:space]
    #   @space = Space.find(params[:space])
    # else
    #   redirect_to @space
    # end
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:day_of_week, :start_time, :end_time, :space_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day_of_week %><br>
    <%= f.text_field :day_of_week %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.text_field :end_time %>
  </div>

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Day of week</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Space</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.day_of_week %></td>
        <td><%= schedule.start_time %></td>
        <td><%= schedule.end_time %></td>
        <td><%= schedule.space %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day of week:</strong>
  <%= @schedule.day_of_week %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<p>
  <strong>Space:</strong>
  <%= @schedule.space %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>